### ISSUE TITLE
服务端多线程序列化报错

### ISSUE THREAD

**Issue by SoNo2Echo** [Kevinnan-teen/Intelligent-Traffic-Based-On-CV#7]
Traceback (most recent call last):
  File "d:\BAG\Intelligent-Traffic-Based-On-CV-version2.0\scripts_2\server_selector.py", line 313, in <module>
    sa = ServerAchieve()
  File "d:\BAG\Intelligent-Traffic-Based-On-CV-version2.0\scripts_2\server_selector.py", line 58, in __init__
    process.start()
  File "C:\Users\10210\.conda\envs\kkdl\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\10210\.conda\envs\kkdl\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\10210\.conda\envs\kkdl\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\10210\.conda\envs\kkdl\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\10210\.conda\envs\kkdl\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object

有老哥知道怎么解决吗？卡住很久了

**Comment by tingyukanfeng** [comment]
兄弟，解决了吗，我也被这个问题卡到了

**Comment by SoNo2Echo** [comment]
没有解决，我直接把检测这一块东西放到客户端了。&nbsp;


Biscuit
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 凌晨0:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kevinnan-teen/Intelligent-Traffic-Based-On-CV] 服务端多线程序列化报错 (Issue #7)





 
兄弟，解决了吗，我也被这个问题卡到了

**Comment by tingyukanfeng** [comment]
好像是系统的问题，必须要使用linux，才行

**Comment by huaijiu99** [comment]
我也遇到这个问题卡住了，可以参考一下您的代码吗

**Comment by SoNo2Echo** [comment]
尝试在Linux环境下运行，Win有问题




Biscuit
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kevinnan-teen/Intelligent-Traffic-Based-On-CV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月30日(星期四) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kevinnan-teen/Intelligent-Traffic-Based-On-CV] 服务端多线程序列化报错 (Issue #7)





 
我也遇到这个问题卡住了，可以参考一下您的代码吗

**Comment by qingxiangjia** [comment]
Traceback (most recent call last):
  File "C:/programSoftware/Python/cattleRecognition/yolo-slowfast/IntelligentTraffic/scripts_2/server_selector2.py", line 288, in <module>
    sa = ServerAchieve()
  File "C:/programSoftware/Python/cattleRecognition/yolo-slowfast/IntelligentTraffic/scripts_2/server_selector2.py", line 54, in __init__
    process.start()
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

Process finished with exit code 1
We have encountered the same problem. Have you solved it yet? I haven't solved this problem yet?
咱俩遇到同一个问题了，请问您解决了吗，我目前还没解决掉这个问题？

**Comment by qingxiangjia** [comment]
换成linux就可以解决掉了吗
