### ISSUE TITLE
启动服务端有错误

### ISSUE THREAD

**Issue by tingyukanfeng** [Kevinnan-teen/Intelligent-Traffic-Based-On-CV#9]
TypeError: can't pickle _thread.lock objects

**Comment by qingxiangjia** [comment]
Traceback (most recent call last):
  File "C:/programSoftware/Python/cattleRecognition/yolo-slowfast/IntelligentTraffic/scripts_2/server_selector2.py", line 288, in <module>
    sa = ServerAchieve()
  File "C:/programSoftware/Python/cattleRecognition/yolo-slowfast/IntelligentTraffic/scripts_2/server_selector2.py", line 54, in __init__
    process.start()
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anzbao-biancheng\anaconda\anzhuangbao\envs\car\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

Process finished with exit code 1
We have encountered the same problem. Have you solved it yet? I haven't solved this problem yet?
咱俩遇到同一个问题了，请问您解决了吗，我目前还没解决掉这个问题？
